### ISSUE TITLE
没有效果

### ISSUE THREAD

**Issue by Eric-Joker** [VictorModi/Lyrics-Getter-Ext#1]
hyperos  Android14
7c04fe2 actionCI版
尝试获取“酷我音乐”歌词（特殊需求）
```
[ 2024-03-19T19:17:52.528    10357: 28158: 28158 I/LSPosed-Bridge  ] Loading legacy module statusbar.finder from /data/app/~~iZE1jp6lVTQHdMYP3TDxOA==/statusbar.finder-y-KzpJA-r6a-cKbzCypLRQ==/base.apk
[ 2024-03-19T19:17:52.577    10357: 28158: 28158 I/LSPosed-Bridge  ]   Loading class statusbar.finder.hook.MainHook
[ 2024-03-19T19:17:52.578    10357: 28158: 28158 E/LSPosed-Bridge  ]     Failed to load class statusbar.finder.hook.MainHook
java.lang.InstantiationException: java.lang.Class<statusbar.finder.hook.MainHook> cannot be instantiated
	at java.lang.Class.newInstance(Native Method)
	at de.robv.android.xposed.XposedInit.initModule(Unknown Source:60)
	at de.robv.android.xposed.XposedInit.loadModule(Unknown Source:144)
	at de.robv.android.xposed.XposedInit.lambda$loadLegacyModules$0(Unknown Source:15)
	at de.robv.android.xposed.XposedInit.b(Unknown Source:0)
	at O0.accept(Unknown Source:13)
	at java.util.ArrayList.forEach(ArrayList.java:1528)
	at de.robv.android.xposed.XposedInit.loadLegacyModules(Unknown Source:12)
	at org.lsposed.lspd.core.Main.forkCommon(Unknown Source:238)
	at com.android.internal.os.Zygote.nativeSpecializeAppProcess(Native Method)
	at com.android.internal.os.Zygote.specializeAppProcess(Unknown Source:1)
	at com.android.internal.os.Zygote.childMain(Unknown Source:364)
	at com.android.internal.os.Zygote.forkSimpleApps(Unknown Source:8)
	at com.android.internal.os.ZygoteConnection.processCommand(Unknown Source:363)
	at com.android.internal.os.ZygoteServer.runSelectLoop(Unknown Source:305)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:367)
```

**Comment by YouCanAi** [comment]
额，目前hook方式修改还没写，无法通过lsposed hook上是正常的，主要是我不会

**Comment by Eric-Joker** [comment]
> 额，目前hook方式修改还没写，无法通过lsposed hook上是正常的，主要是我不会

搜嘎，但是通知捕获对于酷我音乐好像也没有作用（悲）

**Comment by YouCanAi** [comment]
> > 额，目前hook方式修改还没写，无法通过lsposed hook上是正常的，主要是我不会
> 
> 搜嘎，但是通知捕获对于酷我音乐好像也没有作用（悲）

那应该还是爆炸，最近忙咧没时间维护，摆了
